### ISSUE TITLE
episodes/the-one-about-slow-jest-tests

### ISSUE THREAD

**Issue by kbondanza** [runtime-rundown/podcast-site#13]
Hi, 

I love your podcast and listen regularly, just wanted to let you know the link to the episode about slow jest tests 404's on your site. Thank you!

![Screen Shot 2023-02-14 at 4 33 19 PM](https://user-images.githubusercontent.com/8070092/218868212-78a882e9-5667-4c9d-8a70-3017886b429d.png)

![Screen Shot 2023-02-14 at 4 35 08 PM](https://user-images.githubusercontent.com/8070092/218868409-697405ac-fd15-47ec-83c7-6ac5020a6fe4.png)

**Comment by helloitsjoe** [comment]
👋 Thanks so much Kelly! I think we had a bad cached artifact, I just redeployed and it looks like it's working now. Let us know if it's still broken for you, we appreciate the heads up!
